### ISSUE TITLE
Segmentation fault in GUI

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#185]
System information:
OS: Tinycore Linux v6.4
Kernel 3.16.6 i686 (32bit)
gcc v4.9.1
qt v4.8.6 from tinycore repository

This environment works fine with ostinato v0.7.1

In branch master (currently https://github.com/pstavirs/ostinato/commit/daba488d713d37e661478423578bc61c81c41c39) I get a "Segmentation Fault" when starting the GUI. I get this issue with and without optimization.

```
gns3@box:~$ gdb ostinato
GNU gdb (GDB) 7.5.1
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-pc-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bin/ostinato...done.
(gdb) run
Starting program: /usr/local/bin/ostinato
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

Program received signal SIGSEGV, Segmentation fault.
0xb7294239 in std::string::_Rep::_M_grab(std::allocator<char> const&, std::allocator<char> const&) () from /usr/lib/libstdc++.so.6
(gdb) bt
#0  0xb7294239 in std::string::_Rep::_M_grab(std::allocator<char> const&, std::allocator<char> const&) () from /usr/lib/libstdc++.so.6
#1  0xb72942c6 in std::string::assign(std::string const&) ()
   from /usr/lib/libstdc++.so.6
#2  0x08110aba in OstProto::FileMagic::set_value (this=0xbffffa8c, value=...)
    at fileformat.pb.h:1961
#3  0x0813b4cc in NativeFileFormat::NativeFileFormat (
    this=0x83c1f60 <ossnFileFormat>) at nativefileformat.cpp:61
#4  0x081154d1 in OssnFileFormat::OssnFileFormat (
    this=0x83c1f60 <ossnFileFormat>) at ossnfileformat.cpp:25
#5  0x08115c53 in __static_initialization_and_destruction_0 (__initialize_p=1,
    __priority=65535) at ossnfileformat.cpp:22
#6  0x08115c95 in _GLOBAL__sub_I_ossnfileformat.cpp(void) ()
    at ossnfileformat.cpp:91
#7  0x082ad491 in __libc_csu_init ()
#8  0xb709fc8e in __libc_start_main () from /lib/libc.so.6
#9  0x08061fe1 in _start () at ../sysdeps/i386/start.S:115
(gdb)
(gdb)
(gdb)
(gdb) b NativeFileFormat::NativeFileFormat
Breakpoint 1 at 0x813b4a1: file nativefileformat.cpp, line 58.
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y

Starting program: /usr/local/bin/ostinato
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

Breakpoint 1, NativeFileFormat::NativeFileFormat (
    this=0x83c1f60 <ossnFileFormat>) at nativefileformat.cpp:58
58          OstProto::FileMagic magic;
(gdb) n
59          OstProto::FileChecksum cksum;
(gdb) n
61          magic.set_value(kFileMagicValue);
(gdb) p kFileMagicValue
$1 = {static npos = <optimized out>,
  _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x0}}
(gdb) n

Program received signal SIGSEGV, Segmentation fault.
0xb7294239 in std::string::_Rep::_M_grab(std::allocator<char> const&, std::allocator<char> const&) () from /usr/lib/libstdc++.so.6
(gdb)
```

For me it looks like kFileMagicValue is not initialized.

After trying several older commit, I found that the latest working commit is https://github.com/pstavirs/ostinato/commit/5b46bdd8fc8d3f04c20c203875b0133709abf64a . I didn't test it extensively, at least the GUI is starting fine. GDB shows, that the variable kFileMagicValue is initialized.

```
(gdb) b FileFormat::FileFormat
Breakpoint 1 at 0x80c98ad: file fileformat.cpp, line 36.
(gdb) run
Starting program: /usr/local/bin/ostinato
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

Breakpoint 1, FileFormat::FileFormat (this=0x83b8d40 <fileFormat>)
    at fileformat.cpp:36
36      FileFormat::FileFormat()
(gdb) p kFileMagicValue
$1 = {static npos = <optimized out>,
  _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x83c2444 "\247\267OSTINATO"}}
(gdb)
```

The next commit https://github.com/pstavirs/ostinato/commit/c98104f07855c5a04ee8852500ed07449869f7fb shows the same segmentation fault in NativeFileFormat::NativeFileFormat as the current master.

**Comment by pstavirs** [comment]
Thanks for the bug report and gdb traces Bernhard. They are very helpful.

I think I may have an idea of what is happening here, but I don't fully understand it yet. Will investigate a bit more and get back.

**Comment by pstavirs** [comment]
Commit 78957a0  should have fixed this.

Can you check and confirm?

**Comment by ehlers** [comment]
Confirmed, now the GUI starts without any problems.

Tomorrow I will start testing the new functions (session and device emulation).

**Comment by pstavirs** [comment]
Thanks for the confirmation, Bernhard!
